# let's import Numpy first


In [4]:
import numpy as np
x = np.array([1,3,4,6,8])
x

array([1, 3, 4, 6, 8])

In [6]:
type(x)
x.ndim # one dimensional

1

In [7]:
x.shape

(5,)

In [8]:
x.size

5

In [10]:
x.dtype # data type

dtype('int64')

# Accessing Element in our array

In [11]:
x[0,]

1

In [12]:
x [:4]

array([1, 3, 4, 6])

In [13]:
ls

'1 Pandas.ipynb'  '2 Numpy.ipynb'   README.md


In [14]:
np.save('x', x) # save 

In [15]:
ls

'1 Pandas.ipynb'  '2 Numpy.ipynb'   README.md   x.npy


In [16]:
np.load("x.npy")

array([1, 3, 4, 6, 8])